language: node_js
node_js:
  - 0.12
addons:
  firefox: "39.0"
env:
  global:
    - secure: "FVrV50Q9PSDpCuNPxjNSMneGmQLOpuKrGngU7Q9JJH2G0ktHSyveRtB1fJQ6xTa7ZKA/uf8WeWOzXWTLw4p/ieh741WmGKfzJ+Q8UXOyK0Qr/pt9oW7gLl+/9IWE5szREa/DTlN93ekD3DAYFTTKT4YaK8lNSF4IAqjv07kVwTrCNHZ0i6GhQjGVrOSkdTCO8JgKBY4b9XxSTJtrdD/xWlZQtFXozB49shZ/9MaA6QQK+DK/g/EdzI0CnMgrYp9XyMGAWOkrUV8n47XaE+BvsEemtP0HvDYHwVhMMr6GclMHblNjB8j0LVcMZADWcF9CfHuLSzSDpHXoAEPl9yF9+5aQ7XslDcv9IwA7hy5ZFVPrs5j2DEB/sIc6zsm9MXtlNm7I3r8bd3wkn0UB7lNMYp5z9UnGWhdD8wynCQfm78djUfKQoucrN5im/aOvyoKTxbbup7MphtAUaz7KUCijenYyIhBFH3MKfpaGxs5fV362HmjSyWg6TCYrDiM1zSbUsNwnJzX/okc1sLupK6Tr8OhJ6ka5CSwA0uUurAnO15aqAq6XSpW7qEGcDVY6t1/F8nM71wEmmXsTs7wCgFY48W38Dc/WGBGh26WAU717nfwuNpgJmgbx3TsUtKw7mMEKLi5RwsQx9Jr2PARIXBHBTkHSCvZFbAm7X0VZ0HpSO9U="
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - node_modules/.bin/bower i
script: ./node_modules/.bin/preprocess ./test/src/message.spec.js -KARMA=true > ./test/message.spec.js && ./node_modules/.bin/karma start --browsers Firefox --single-run